# Generated by Django 6.0.1 on 2026-01-30 23:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(help_text='Photo of the second-hand fabric', upload_to='fabrics/')),
                ('length_inches', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('width_inches', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_PROGRESS', 'In Progress'), ('SCRAP', 'Scrap Pile')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom'), ('FULL', 'Full Body')], max_length=10)),
                ('envelope_image', models.ImageField(help_text='Photo of the back of the pattern envelope', upload_to='patterns/')),
                ('is_full_length', models.BooleanField(default=False, help_text='Check if inseam matching is required (e.g., long pants)')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bust_chest', models.DecimalField(decimal_places=2, help_text='Inches', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('waist', models.DecimalField(decimal_places=2, help_text='Inches', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('hips', models.DecimalField(decimal_places=2, help_text='Inches', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('shoulder_width', models.DecimalField(decimal_places=2, help_text='Inches', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('inseam', models.DecimalField(decimal_places=2, help_text='Inches', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('height_total', models.DecimalField(decimal_places=2, help_text='Inches', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatternSizeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(help_text='e.g., Size 10', max_length=50)),
                ('max_bust', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('max_waist', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('max_hips', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('max_shoulder', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('max_inseam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('required_width', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('required_length', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_requirements', to='core.pattern')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_used', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fabric')),
                ('pattern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pattern')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
