# Generated by Django 6.0.1 on 2026-01-31 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_patternsizerequirement_max_bust_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='envelope_image',
        ),
    ]
